In [2]:
!pip install torch

     ------------------------------------ 162.5/162.5 MB 447.0 kB/s eta 0:00:00



[notice] A new release of pip available: 22.3.1 -> 23.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [35]:
import torch
import numpy as np

In [4]:
torch.zeros([3,4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [5]:
torch.ones([2,3,4])

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [7]:
torch.Tensor([[1,2,3],
            [4,5,6],
            [7,8,9]])

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [8]:
x = torch.Tensor([[1,2,3],
            [4,5,6],
            [7,8,9]])

In [9]:
x.size()

torch.Size([3, 3])

In [11]:
x.shape

torch.Size([3, 3])

In [12]:
x[0]

tensor([1., 2., 3.])

In [13]:
x[0,0]

tensor(1.)

In [14]:
x + 10

tensor([[11., 12., 13.],
        [14., 15., 16.],
        [17., 18., 19.]])

In [15]:
x ** 2

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])

In [20]:
y = torch.Tensor([[3,2,1],
                [6,5,4],
                [9,8,7]])
y

tensor([[3., 2., 1.],
        [6., 5., 4.],
        [9., 8., 7.]])

In [21]:
x + y

tensor([[ 4.,  4.,  4.],
        [10., 10., 10.],
        [16., 16., 16.]])

In [22]:
x * y

tensor([[ 3.,  4.,  3.],
        [24., 25., 24.],
        [63., 64., 63.]])

In [23]:
x / y

tensor([[0.3333, 1.0000, 3.0000],
        [0.6667, 1.0000, 1.5000],
        [0.7778, 1.0000, 1.2857]])

In [24]:
x % y

tensor([[1., 0., 0.],
        [4., 0., 2.],
        [7., 0., 2.]])

In [25]:
torch.exp(x)

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01],
        [5.4598e+01, 1.4841e+02, 4.0343e+02],
        [1.0966e+03, 2.9810e+03, 8.1031e+03]])

In [26]:
x > 3

tensor([[False, False, False],
        [ True,  True,  True],
        [ True,  True,  True]])

In [27]:
mask = x > 3

In [28]:
x[mask]

tensor([4., 5., 6., 7., 8., 9.])

In [29]:
x[x > 3]

tensor([4., 5., 6., 7., 8., 9.])

In [30]:
X = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
limit = int(input())

larger_than_limit_sum = X[X > limit].sum()

print(larger_than_limit_sum)

1
tensor(44)


In [31]:
y = x.clone()
y[0, 0] = 999
print(x)
print(y)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([[999.,   2.,   3.],
        [  4.,   5.,   6.],
        [  7.,   8.,   9.]])


In [32]:
x.dtype

torch.float32

In [34]:
x = x.double()
print(x)
x = x.int()
print(x)
x = x.float()
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], dtype=torch.float64)
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32)
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [36]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [37]:
a = torch.from_numpy(a)
a

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]], dtype=torch.int32)

In [38]:
a = a.numpy()
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [40]:
x = torch.rand([2,3])
x

tensor([[0.7255, 0.3369, 0.8851],
        [0.1553, 0.6966, 0.4536]])

In [41]:
torch.cuda.is_available()

False